<?php
/**
 * TL_ROOT/system/modules/sessionform/languages/ja/default.php 
 * 
 * Contao extension: sessionform 1.1.1 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2009-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FFL']['sessionText']['0'] = "セッションからテキスト";
$GLOBALS['TL_LANG']['FFL']['sessionText']['1'] = "以前のフォームからテキスト入力やテキストエリアを表示します。";
$GLOBALS['TL_LANG']['FFL']['sessionOption']['0'] = "セッションから選択肢";
$GLOBALS['TL_LANG']['FFL']['sessionOption']['1'] = "以前のフォームからテキスト選択やチェックボックスを表示します。";
$GLOBALS['TL_LANG']['FFL']['sessionCalculator']['0'] = "セッションから計算";
$GLOBALS['TL_LANG']['FFL']['sessionCalculator']['1'] = "以前のフォームの複数のテキスト入力を元に値を表示します。";
$GLOBALS['TL_LANG']['FFL']['hiddenOption']['0'] = "隠した選択肢";
$GLOBALS['TL_LANG']['FFL']['hiddenOption']['1'] = "フォームに表示しない複数の入力項目です。";
 
?>
