<?php
/**
 * TL_ROOT/system/modules/sessionform/languages/ja/modules.php 
 * 
 * Contao extension: sessionform 1.1.1 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2009-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['resetFormData']['0'] = "フォームデータの削除";
$GLOBALS['TL_LANG']['FMD']['resetFormData']['1'] = "ユーザーのセッションからデータを削除します。フォームを提出した後のページに位置すべきです。";
$GLOBALS['TL_LANG']['MOD']['sessionform']['0'] = "複数ページのフォーム";
 
?>
