<?php
/**
 * TL_ROOT/system/modules/sessionform/languages/ja/tl_form_field.php 
 * 
 * Contao extension: sessionform 1.1.1 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2009-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_form_field']['calculation']['0'] = "計算";
$GLOBALS['TL_LANG']['tl_form_field']['calculation']['1'] = "有効な計算式を入力してください。フォームの入力項目の値に{filedname}という表記を使用してください。";
$GLOBALS['TL_LANG']['tl_form_field']['currency']['0'] = "通貨記号";
$GLOBALS['TL_LANG']['tl_form_field']['currency']['1'] = "通貨記号を入力してください。";
$GLOBALS['TL_LANG']['tl_form_field']['currencyPosition']['0'] = "通貨記号の位置";
$GLOBALS['TL_LANG']['tl_form_field']['currencyPosition']['1'] = "計算結果に通貨記号を表示したい場合の位置を左または右から選択してください。";
$GLOBALS['TL_LANG']['tl_form_field']['loadSession']['0'] = "セッションのデータを読み込み";
$GLOBALS['TL_LANG']['tl_form_field']['loadSession']['1'] = "以前のフォームからデータを読みたい場合に選択してください。";
 
?>
